# CMake generated Testfile for 
# Source directory: /home/wubu/WuBuOffice
# Build directory: /home/wubu/WuBuOffice/build-asan
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(wubunote_ctrl "/home/wubu/WuBuOffice/build-asan/test_wubunote_ctrl")
set_tests_properties(wubunote_ctrl PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;291;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(wubunote "/home/wubu/WuBuOffice/build-asan/test_wubunote")
set_tests_properties(wubunote PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;296;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(wubuzip_crc "/home/wubu/WuBuOffice/build-asan/test_wubuzip")
set_tests_properties(wubuzip_crc PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;302;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(inflate "/home/wubu/WuBuOffice/build-asan/test_inflate")
set_tests_properties(inflate PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;306;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(formula "/home/wubu/WuBuOffice/build-asan/test_formula")
set_tests_properties(formula PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;311;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(model "/home/wubu/WuBuOffice/build-asan/test_model")
set_tests_properties(model PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;315;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(doc_cache "/home/wubu/WuBuOffice/build-asan/test_doc_cache")
set_tests_properties(doc_cache PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;319;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(load_async "/home/wubu/WuBuOffice/build-asan/test_load_async")
set_tests_properties(load_async PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;323;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(deflate_roundtrip "/home/wubu/WuBuOffice/build-asan/test_deflate_roundtrip")
set_tests_properties(deflate_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;327;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(cold_start "/home/wubu/WuBuOffice/build-asan/test_cold_start")
set_tests_properties(cold_start PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;331;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(model_io_roundtrip "/home/wubu/WuBuOffice/build-asan/test_model_io_roundtrip")
set_tests_properties(model_io_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;335;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(wubuxml_parser "/home/wubu/WuBuOffice/build-asan/test_wubuxml_parser")
set_tests_properties(wubuxml_parser PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;340;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(reader_roundtrip "/home/wubu/WuBuOffice/build-asan/test_reader")
set_tests_properties(reader_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;345;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(extract "/home/wubu/WuBuOffice/build-asan/test_extract")
set_tests_properties(extract PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;350;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(edit_roundtrip "/home/wubu/WuBuOffice/build-asan/test_edit")
set_tests_properties(edit_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;355;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(conformance "/home/wubu/WuBuOffice/build-asan/test_conformance")
set_tests_properties(conformance PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;361;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(foreign_read "/home/wubu/WuBuOffice/build-asan/test_foreign")
set_tests_properties(foreign_read PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;369;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(cell_read "/home/wubu/WuBuOffice/build-asan/test_cell_read")
set_tests_properties(cell_read PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;374;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(cell_cycle "/home/wubu/WuBuOffice/build-asan/test_cell_cycle")
set_tests_properties(cell_cycle PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;379;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(csv "/home/wubu/WuBuOffice/build-asan/test_csv")
set_tests_properties(csv PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;384;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(md "/home/wubu/WuBuOffice/build-asan/test_md")
set_tests_properties(md PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;389;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(rtf_json "/home/wubu/WuBuOffice/build-asan/test_rtf_json")
set_tests_properties(rtf_json PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;394;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(odf "/home/wubu/WuBuOffice/build-asan/test_odf")
set_tests_properties(odf PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;400;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(convert "/home/wubu/WuBuOffice/build-asan/test_convert")
set_tests_properties(convert PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;408;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(readers "/home/wubu/WuBuOffice/build-asan/test_readers")
set_tests_properties(readers PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;416;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(legacy_pdf "/home/wubu/WuBuOffice/build-asan/test_legacy_pdf")
set_tests_properties(legacy_pdf PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;427;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(flat_epub "/home/wubu/WuBuOffice/build-asan/test_flat_epub")
set_tests_properties(flat_epub PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;438;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(wubufont "/home/wubu/WuBuOffice/build-asan/test_wubufont")
set_tests_properties(wubufont PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;443;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(wubuocr "/home/wubu/WuBuOffice/build-asan/test_wubuocr")
set_tests_properties(wubuocr PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;448;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(wubuocr_recognize "/home/wubu/WuBuOffice/build-asan/test_wubuocr_recognize")
set_tests_properties(wubuocr_recognize PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;453;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(fontbank "/home/wubu/WuBuOffice/build-asan/test_fontbank")
set_tests_properties(fontbank PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;458;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(gauntlet "/home/wubu/WuBuOffice/build-asan/test_gauntlet")
set_tests_properties(gauntlet PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;463;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(wubutui "/home/wubu/WuBuOffice/build-asan/test_wubutui")
set_tests_properties(wubutui PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;468;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(wubuview "/home/wubu/WuBuOffice/build-asan/test_wubuview")
set_tests_properties(wubuview PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;474;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(wubuview_ctrl "/home/wubu/WuBuOffice/build-asan/test_wubuview_ctrl")
set_tests_properties(wubuview_ctrl PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;487;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(wubusvg "/home/wubu/WuBuOffice/build-asan/test_wubusvg")
set_tests_properties(wubusvg PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;492;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(wubudoc "/home/wubu/WuBuOffice/build-asan/test_wubudoc")
set_tests_properties(wubudoc PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;497;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(drop "/home/wubu/WuBuOffice/build-asan/test_drop")
set_tests_properties(drop PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;502;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
add_test(wubusvg_agent "/home/wubu/WuBuOffice/build-asan/test_wubusvg_agent")
set_tests_properties(wubusvg_agent PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/CMakeLists.txt;507;add_test;/home/wubu/WuBuOffice/CMakeLists.txt;0;")
