# CMake generated Testfile for 
# Source directory: /home/wubu/WuBuOffice
# Build directory: /home/wubu/WuBuOffice/build-plugin
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("src")
subdirs("src/wubucrdt")
subdirs("src/wubuhistory")
subdirs("src/wubusync")
subdirs("src/wubucol")
subdirs("src/wubuvars")
subdirs("src/wubulang")
subdirs("src/wubucaption")
subdirs("src/wubuwatermark")
subdirs("src/wubufocus")
subdirs("src/wubudyslexia")
subdirs("src/wubuscope")
subdirs("src/wubua11ytree")
subdirs("src/wubueqnum")
subdirs("src/wubuheading")
subdirs("src/wubucite")
subdirs("src/wubuhash")
subdirs("src/wubusig")
subdirs("src/wuburedact")
subdirs("src/wubucsv")
subdirs("src/wubupasteplain")
subdirs("src/wuburtf")
subdirs("src/wubua11yannounce")
subdirs("src/wubuform")
subdirs("src/wubuexp_png")
subdirs("src/wubupdfextract")
subdirs("src/wubuxps")
subdirs("src/wubuaislot")
subdirs("src/wubusandbox")
subdirs("src/wubufmtpaint")
subdirs("src/wubunesttab")
subdirs("src/wubupdfform")
subdirs("apps")
subdirs("tools")
subdirs("tests")
