add_library(wubuconnector STATIC wubuconnector.c)
target_include_directories(wubuconnector PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_compile_options(wubuconnector PRIVATE -Wall -Wextra -Wpedantic)
add_executable(test_wubuconnector test_wubuconnector.c)
target_link_libraries(test_wubuconnector PRIVATE wubuconnector)
target_compile_options(test_wubuconnector PRIVATE -Wall -Wextra -Wpedantic)
add_test(NAME wubuconnector COMMAND test_wubuconnector)
set_tests_properties(wubuconnector PROPERTIES LABELS "wubuconnector;libs")
