#include "word.h"
#include "assemble.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* wubuword: emit a richer .docx (headings, bold, table) from scratch. */
int wubuword_main(int argc, char **argv) {
    const char *outpath = (argc > 1) ? argv[1] : "WuBuOffice.docx";

    wubuword_doc *d = wubuword_create();
    wubuword_para(d, "Title", 1, "WuBu Office — Rich Document");
    wubuword_para(d, "Heading1", 0, "Introduction");
    wubuword_para(d, NULL, 0, "Generated by WuBuOffice, a ground-up C11 SLERM of OOXML. No forks, no .NET.");
    wubuword_para(d, "Heading2", 0, "Features");
    wubuword_para(d, NULL, 1, "Headings and bold runs are supported.");
    wubuword_para(d, NULL, 0, "Tables render with single borders:");

    wubuword_table_begin(d);
    wubuword_cell(d, 1, "Layer");
    wubuword_cell(d, 1, "Purpose");
    wubuword_cell(d, 0, "wubuzip"); wubuword_cell(d, 0, "ZIP container + inflate");
    wubuword_cell(d, 0, "wubuxml"); wubuword_cell(d, 0, "Streaming XML writer");
    wubuword_cell(d, 0, "wubuoxml"); wubuword_cell(d, 0, "OPC package");
    wubuword_table_end(d);

    wubuword_para(d, "Heading2", 0, "Roadmap");
    wubuword_list_begin(d, "bullet");
    wubuword_list_item(d, "Images and headers/footers");
    wubuword_list_item(d, "Hyperlinks and comments");
    wubuword_list_item(d, "Nested and multilevel lists");
    wubuword_list_end(d);
    wubuword_para(d, NULL, 0, "Ordered steps:");
    wubuword_list_begin(d, "number");
    wubuword_list_item(d, "Parse the spec");
    wubuword_list_item(d, "Write the writer");
    wubuword_list_item(d, "Validate the output");
    wubuword_list_end(d);

    if (wubuword_assemble_doc(outpath, d) != 0) {
        fprintf(stderr, "wubuword: assemble failed\n"); wubuword_free(d); return 1;
    }
    fprintf(stderr, "wubuword: wrote %s (used_lists=%d)\n", outpath, wubuword_used_lists(d));
    wubuword_free(d);
    return 0;
}
