#ifndef _POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
#endif
#include "../wubuoxml/package.h"
#include "../wubuxml/xml.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Build the WordprocessingML document.xml part in memory. */
static char *build_document_xml(const char *title, const char *body) {
    char *buf = NULL; size_t len = 0; FILE *m = open_memstream(&buf, &len);
    wubuxml_writer *w = wubuxml_create(m);

    wubuxml_open(w, "w:document");
    wubuxml_set_attr(w, "xmlns:w",
        "http://schemas.openxmlformats.org/wordprocessingml/2006/main");
    wubuxml_open(w, "w:body");
    /* title paragraph */
    wubuxml_open(w, "w:p");
    wubuxml_open(w, "w:r");
    wubuxml_open(w, "w:rPr");
    wubuxml_open(w, "w:b"); wubuxml_close(w);
    wubuxml_close(w);
    wubuxml_open(w, "w:t"); wubuxml_text(w, title); wubuxml_close(w);
    wubuxml_close(w);
    /* body paragraph */
    wubuxml_open(w, "w:p");
    wubuxml_open(w, "w:r");
    wubuxml_open(w, "w:t"); wubuxml_text(w, body); wubuxml_close(w);
    wubuxml_close(w);
    /* section properties */
    wubuxml_open(w, "w:sectPr");
    wubuxml_open(w, "w:pgSz");
    wubuxml_set_attr(w, "w:w", "12240");
    wubuxml_set_attr(w, "w:h", "15840");
    wubuxml_close(w);
    wubuxml_close(w);
    wubuxml_close(w); /* body */
    wubuxml_close(w); /* document */

    wubuxml_destroy(w);
    fflush(m); fclose(m);
    return buf;
}

int main(int argc, char **argv) {
    const char *outpath = (argc > 1) ? argv[1] : "WuBuOffice.docx";
    const char *title = (argc > 2) ? argv[2] : "WuBu Office Document";
    const char *body = (argc > 3) ? argv[3] : "Generated by WuBuOffice — a ground-up C11 reimplementation of OOXML.";

    FILE *out = fopen(outpath, "wb");
    if (!out) { perror("fopen"); return 1; }

    wubuoxml_package *pkg = wubuoxml_create(out);

    /* content types */
    wubuoxml_add_default_type(pkg, "rels", "application/vnd.openxmlformats-package.relationships+xml");
    wubuoxml_add_default_type(pkg, "xml", "application/xml");
    wubuoxml_add_override(pkg, "/word/document.xml",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml");

    /* package relationships */
    wubuoxml_add_relationship(pkg, "",
        "word/document.xml",
        "http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument");

    /* document part */
    char *doc = build_document_xml(title, body);
    size_t doclen = strlen(doc);
    wubuoxml_add_part(pkg, "word/document.xml", doc, doclen);
    free(doc);

    int rc = wubuoxml_finalize(pkg);
    fclose(out);
    if (rc != 0) { fprintf(stderr, "WuBuOffice: package finalize failed\n"); return 1; }

    fprintf(stderr, "WuBuOffice: wrote %s\n", outpath);
    return 0;
}
