#include "word.h"
#include "assemble.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* wubuword: emit a richer .docx (headings, bold, table) from scratch. */
int wubuword_main(int argc, char **argv) {
    const char *outpath = (argc > 1) ? argv[1] : "WuBuOffice.docx";

    wubuword_doc *d = wubuword_create();
    wubuword_para(d, "Title", 1, "WuBu Office — Rich Document");
    wubuword_para(d, "Heading1", 0, "Introduction");
    wubuword_para(d, NULL, 0, "Generated by WuBuOffice, a ground-up C11 SLERM of OOXML. No forks, no .NET.");
    wubuword_para(d, "Heading2", 0, "Features");
    wubuword_para(d, NULL, 1, "Headings and bold runs are supported.");
    wubuword_para(d, NULL, 0, "Tables render with single borders:");

    wubuword_table_begin(d);
    wubuword_cell(d, 1, "Layer");
    wubuword_cell(d, 1, "Purpose");
    wubuword_cell(d, 0, "wubuzip"); wubuword_cell(d, 0, "ZIP container + inflate");
    wubuword_cell(d, 0, "wubuxml"); wubuword_cell(d, 0, "Streaming XML writer");
    wubuword_cell(d, 0, "wubuoxml"); wubuword_cell(d, 0, "OPC package");
    wubuword_table_end(d);

    size_t len = 0;
    char *doc = wubuword_render(d, &len);
    wubuword_free(d);

    if (wubuword_assemble(outpath, doc, len) != 0) {
        fprintf(stderr, "wubuword: assemble failed\n"); free(doc); return 1;
    }
    free(doc);
    fprintf(stderr, "wubuword: wrote %s (%zu bytes of document.xml)\n", outpath, len);
    return 0;
}
