# CMake generated Testfile for 
# Source directory: /home/wubu/WuBuOffice/tests
# Build directory: /home/wubu/WuBuOffice/build-plugin/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(wubuzip_crc "/home/wubu/WuBuOffice/build-plugin/tests/test_wubuzip")
set_tests_properties(wubuzip_crc PROPERTIES  LABELS "zip" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;5;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(inflate "/home/wubu/WuBuOffice/build-plugin/tests/test_inflate")
set_tests_properties(inflate PROPERTIES  LABELS "zip" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;9;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(formula "/home/wubu/WuBuOffice/build-plugin/tests/test_formula")
set_tests_properties(formula PROPERTIES  LABELS "formula" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;14;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(spell "/home/wubu/WuBuOffice/build-plugin/tests/test_spell")
set_tests_properties(spell PROPERTIES  LABELS "spell" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;18;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(base "/home/wubu/WuBuOffice/build-plugin/tests/test_base")
set_tests_properties(base PROPERTIES  LABELS "base" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;22;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(png "/home/wubu/WuBuOffice/build-plugin/tests/test_png")
set_tests_properties(png PROPERTIES  LABELS "png" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;26;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(chart "/home/wubu/WuBuOffice/build-plugin/tests/test_chart")
set_tests_properties(chart PROPERTIES  LABELS "chart" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;30;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(autosave "/home/wubu/WuBuOffice/build-plugin/tests/test_autosave")
set_tests_properties(autosave PROPERTIES  LABELS "autosave" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;34;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(draw "/home/wubu/WuBuOffice/build-plugin/tests/test_draw")
set_tests_properties(draw PROPERTIES  LABELS "draw" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;38;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(wubumath "/home/wubu/WuBuOffice/build-plugin/tests/test_wubumath")
set_tests_properties(wubumath PROPERTIES  LABELS "math" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;42;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(epub "/home/wubu/WuBuOffice/build-plugin/tests/test_epub")
set_tests_properties(epub PROPERTIES  LABELS "epub" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;46;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(epub_model_roundtrip "/home/wubu/WuBuOffice/build-plugin/tests/test_epub_model_roundtrip")
set_tests_properties(epub_model_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;50;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(a11y "/home/wubu/WuBuOffice/build-plugin/tests/test_a11y")
set_tests_properties(a11y PROPERTIES  LABELS "a11y" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;54;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(script "/home/wubu/WuBuOffice/build-plugin/tests/test_script")
set_tests_properties(script PROPERTIES  LABELS "script" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;58;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(model "/home/wubu/WuBuOffice/build-plugin/tests/test_model")
set_tests_properties(model PROPERTIES  LABELS "model" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;62;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(doc_cache "/home/wubu/WuBuOffice/build-plugin/tests/test_doc_cache")
set_tests_properties(doc_cache PROPERTIES  LABELS "model" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;66;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(load_async "/home/wubu/WuBuOffice/build-plugin/tests/test_load_async")
set_tests_properties(load_async PROPERTIES  LABELS "model" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;70;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(deflate_roundtrip "/home/wubu/WuBuOffice/build-plugin/tests/test_deflate_roundtrip")
set_tests_properties(deflate_roundtrip PROPERTIES  LABELS "zip" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;74;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(cold_start "/home/wubu/WuBuOffice/build-plugin/tests/test_cold_start")
set_tests_properties(cold_start PROPERTIES  LABELS "model" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;78;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(model_io_roundtrip "/home/wubu/WuBuOffice/build-plugin/tests/test_model_io_roundtrip")
set_tests_properties(model_io_roundtrip PROPERTIES  LABELS "model" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;82;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(wubuxml_parser "/home/wubu/WuBuOffice/build-plugin/tests/test_wubuxml_parser")
set_tests_properties(wubuxml_parser PROPERTIES  LABELS "oxml" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;87;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(reader_roundtrip "/home/wubu/WuBuOffice/build-plugin/tests/test_reader")
set_tests_properties(reader_roundtrip PROPERTIES  LABELS "oxml" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;92;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(extract "/home/wubu/WuBuOffice/build-plugin/tests/test_extract")
set_tests_properties(extract PROPERTIES  LABELS "oxml" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;97;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(edit_roundtrip "/home/wubu/WuBuOffice/build-plugin/tests/test_edit")
set_tests_properties(edit_roundtrip PROPERTIES  LABELS "oxml" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;102;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(conformance "/home/wubu/WuBuOffice/build-plugin/tests/test_conformance")
set_tests_properties(conformance PROPERTIES  LABELS "oxml" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;108;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(foreign_read "/home/wubu/WuBuOffice/build-plugin/tests/test_foreign")
set_tests_properties(foreign_read PROPERTIES  LABELS "oxml" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;115;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(cell_read "/home/wubu/WuBuOffice/build-plugin/tests/test_cell_read")
set_tests_properties(cell_read PROPERTIES  LABELS "cell" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;120;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(cell_cycle "/home/wubu/WuBuOffice/build-plugin/tests/test_cell_cycle")
set_tests_properties(cell_cycle PROPERTIES  LABELS "cell" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;125;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(cell_merge "/home/wubu/WuBuOffice/build-plugin/tests/test_cell_merge")
set_tests_properties(cell_merge PROPERTIES  LABELS "cell" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;130;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(csv "/home/wubu/WuBuOffice/build-plugin/tests/test_csv")
set_tests_properties(csv PROPERTIES  LABELS "cell" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;135;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(md "/home/wubu/WuBuOffice/build-plugin/tests/test_md")
set_tests_properties(md PROPERTIES  LABELS "word" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;140;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(rtf_json "/home/wubu/WuBuOffice/build-plugin/tests/test_rtf_json")
set_tests_properties(rtf_json PROPERTIES  LABELS "word" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;145;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(odf "/home/wubu/WuBuOffice/build-plugin/tests/test_odf")
set_tests_properties(odf PROPERTIES  LABELS "odf" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;151;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(convert "/home/wubu/WuBuOffice/build-plugin/tests/test_convert")
set_tests_properties(convert PROPERTIES  LABELS "odf" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;159;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(conv_model "/home/wubu/WuBuOffice/build-plugin/tests/test_conv_model")
set_tests_properties(conv_model PROPERTIES  LABELS "convert;apps" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;166;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(word_lists "/home/wubu/WuBuOffice/build-plugin/tests/test_word_lists")
set_tests_properties(word_lists PROPERTIES  LABELS "word" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;173;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(readers "/home/wubu/WuBuOffice/build-plugin/tests/test_readers")
set_tests_properties(readers PROPERTIES  LABELS "word" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;181;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(legacy_pdf "/home/wubu/WuBuOffice/build-plugin/tests/test_legacy_pdf")
set_tests_properties(legacy_pdf PROPERTIES  LABELS "word" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;191;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(flat_epub "/home/wubu/WuBuOffice/build-plugin/tests/test_flat_epub")
set_tests_properties(flat_epub PROPERTIES  LABELS "word" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;201;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(wubufont "/home/wubu/WuBuOffice/build-plugin/tests/test_wubufont")
set_tests_properties(wubufont PROPERTIES  LABELS "font" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;206;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(wubuocr "/home/wubu/WuBuOffice/build-plugin/tests/test_wubuocr")
set_tests_properties(wubuocr PROPERTIES  LABELS "ocr" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;211;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(crnn_transcribe "/home/wubu/WuBuOffice/build-plugin/tests/test_crnn_transcribe")
set_tests_properties(crnn_transcribe PROPERTIES  LABELS "ocr" WORKING_DIRECTORY "/home/wubu/WuBuOffice" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;217;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(crnn_transcribe_full "/home/wubu/WuBuOffice/build-plugin/tests/test_crnn_transcribe_full")
set_tests_properties(crnn_transcribe_full PROPERTIES  LABELS "ocr" WORKING_DIRECTORY "/home/wubu/WuBuOffice" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;224;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(columns "/home/wubu/WuBuOffice/build-plugin/tests/test_columns")
set_tests_properties(columns PROPERTIES  LABELS "ocr" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;231;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(imageops "/home/wubu/WuBuOffice/build-plugin/tests/test_imageops")
set_tests_properties(imageops PROPERTIES  LABELS "ocr" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;237;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(xlsx "/home/wubu/WuBuOffice/build-plugin/tests/test_xlsx")
set_tests_properties(xlsx PROPERTIES  LABELS "ocr" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;243;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(docfmt2 "/home/wubu/WuBuOffice/build-plugin/tests/test_docfmt2")
set_tests_properties(docfmt2 PROPERTIES  LABELS "ocr" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;249;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(pdfua "/home/wubu/WuBuOffice/build-plugin/tests/test_pdfua")
set_tests_properties(pdfua PROPERTIES  LABELS "ocr" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;255;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(nfc "/home/wubu/WuBuOffice/build-plugin/tests/test_nfc")
set_tests_properties(nfc PROPERTIES  LABELS "ocr" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;261;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(imgops "/home/wubu/WuBuOffice/build-plugin/tests/test_imgops")
set_tests_properties(imgops PROPERTIES  LABELS "ocr" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;267;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(docfmt "/home/wubu/WuBuOffice/build-plugin/tests/test_docfmt")
set_tests_properties(docfmt PROPERTIES  LABELS "ocr" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;273;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(ocr_realpage "/home/wubu/WuBuOffice/build-plugin/tests/test_ocr_realpage")
set_tests_properties(ocr_realpage PROPERTIES  LABELS "ocr" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;278;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(wubuocr_recognize "/home/wubu/WuBuOffice/build-plugin/tests/test_wubuocr_recognize")
set_tests_properties(wubuocr_recognize PROPERTIES  LABELS "ocr" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;283;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(fontbank "/home/wubu/WuBuOffice/build-plugin/tests/test_fontbank")
set_tests_properties(fontbank PROPERTIES  LABELS "ocr" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;288;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(gauntlet "/home/wubu/WuBuOffice/build-plugin/tests/test_gauntlet")
set_tests_properties(gauntlet PROPERTIES  LABELS "ocr" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;293;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(latin1 "/home/wubu/WuBuOffice/build-plugin/tests/test_latin1")
set_tests_properties(latin1 PROPERTIES  LABELS "ocr" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;298;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(wubunote_ctrl "/home/wubu/WuBuOffice/build-plugin/tests/test_wubunote_ctrl")
set_tests_properties(wubunote_ctrl PROPERTIES  LABELS "note" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;305;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(wubunote "/home/wubu/WuBuOffice/build-plugin/tests/test_wubunote")
set_tests_properties(wubunote PROPERTIES  LABELS "note" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;309;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(wubuview "/home/wubu/WuBuOffice/build-plugin/tests/test_wubuview")
set_tests_properties(wubuview PROPERTIES  LABELS "view" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;315;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(wubuview_ctrl "/home/wubu/WuBuOffice/build-plugin/tests/test_wubuview_ctrl")
set_tests_properties(wubuview_ctrl PROPERTIES  LABELS "view" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;320;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(wubusvg "/home/wubu/WuBuOffice/build-plugin/tests/test_wubusvg")
set_tests_properties(wubusvg PROPERTIES  LABELS "svg" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;325;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(wubudoc "/home/wubu/WuBuOffice/build-plugin/tests/test_wubudoc")
set_tests_properties(wubudoc PROPERTIES  LABELS "doc" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;330;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(drop "/home/wubu/WuBuOffice/build-plugin/tests/test_drop")
set_tests_properties(drop PROPERTIES  LABELS "doc" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;335;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(wubusvg_agent "/home/wubu/WuBuOffice/build-plugin/tests/test_wubusvg_agent")
set_tests_properties(wubusvg_agent PROPERTIES  LABELS "svg" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;340;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(gpu_blas "/home/wubu/WuBuOffice/build-plugin/tests/test_gpu_blas")
set_tests_properties(gpu_blas PROPERTIES  LABELS "gpu" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;345;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(gru_gpu_gradcheck "/home/wubu/WuBuOffice/build-plugin/tests/test_gru_gpu")
set_tests_properties(gru_gpu_gradcheck PROPERTIES  LABELS "gpu" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;351;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(gemm_nt "/home/wubu/WuBuOffice/build-plugin/tests/test_gemm_nt")
set_tests_properties(gemm_nt PROPERTIES  LABELS "gpu" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;355;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(gru_cmp "/home/wubu/WuBuOffice/build-plugin/tests/test_gru_cmp")
set_tests_properties(gru_cmp PROPERTIES  LABELS "gpu" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;361;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(layout "/home/wubu/WuBuOffice/build-plugin/tests/test_layout")
set_tests_properties(layout PROPERTIES  LABELS "layout" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;442;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(exp "/home/wubu/WuBuOffice/build-plugin/tests/test_exp")
set_tests_properties(exp PROPERTIES  LABELS "exp" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;447;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(settings "/home/wubu/WuBuOffice/build-plugin/tests/test_settings")
set_tests_properties(settings PROPERTIES  LABELS "settings" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;453;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
add_test(toc "/home/wubu/WuBuOffice/build-plugin/tests/test_toc")
set_tests_properties(toc PROPERTIES  LABELS "toc" _BACKTRACE_TRIPLES "/home/wubu/WuBuOffice/tests/CMakeLists.txt;463;add_test;/home/wubu/WuBuOffice/tests/CMakeLists.txt;0;")
