add_library(wubumasterslide STATIC wubumasterslide.c)
target_include_directories(wubumasterslide PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_compile_options(wubumasterslide PRIVATE -Wall -Wextra -Wpedantic)
add_executable(test_wubumasterslide test_wubumasterslide.c)
target_link_libraries(test_wubumasterslide PRIVATE wubumasterslide m)
target_compile_options(test_wubumasterslide PRIVATE -Wall -Wextra -Wpedantic)
add_test(NAME wubumasterslide COMMAND test_wubumasterslide)
set_tests_properties(wubumasterslide PROPERTIES LABELS "wubumasterslide;libs")
